POST http://localhost:4000/loan/createLoan
content-type: application/json

{ 
      "loanDate": "2021-06-01", 
      "returnDate":"", 
      "status": "pending", 
      "userId": "3", 
      "toolId" : "4"
}
