POST http://localhost:4000/auth/createUser
content-type: application/json

{ 
    "fullName":"juancho",
    "documentType":"CC",
    "documentNumber":"84546343434",
    "password":"Micontrasena",
    "fileId":"2312301294",
    "role":"Admnistrador",
    "status":"Activo" 
}