POST http://localhost:4000/tool/createTool
content-type: application/json

# { 
#      "image":"mi-imagen.png", 
#      "name":"taladro", 
#      "brand":"bosch", 
#      "total":"5", 
#      "available":"5", 
#      "price":"500000", 
#      "status":"Activo"
# }

{ 
     "image":"mi-imagen.png", 
     "name":"pulidora", 
     "brand":"dwalt", 
     "total":"2", 
     "available":"5", 
     "price":"500000", 
     "status":"Activo"
}
